FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl procps && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY healthcheck.sh .

RUN chmod +x healthcheck.sh

EXPOSE 5000

HEALTHCHECK --interval=15s --timeout=5s --start-period=10s --retries=2 \
CMD ./healthcheck.sh

CMD ["python","app.py"]
